apiVersion: v1
kind: Pod
metadata: 
  name: mysqlserver
spec:
  containers:
  - image: mysql
    name: mysqlserver
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysqlvolume
    env:
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
      - name: MYSQL_ROOT_PASSWORD
        value: password

  volumes:
  - name: mysqlvolume
    hostPath:
      path: /data-volume
      type: Directory

