apiVersion: v1
kind: Pod
metadata:
  name: webapp3
  labels:
    app: web
spec:
  containers:
  - name: webapp3
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red
